#!/usr/bin/env python
# -*- coding: utf-8 -*-
#########################################################################
# File Name: qsub.py
# Author: jyxu
# mail: ahcigar@foxmail.com
# Created Time: 日  3/18 22:00:16 2018
#########################################################################
print('29000.master')
